<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="em_AU">

<head>

    <base href="<?=$this->application->url();?>/" target="_top"/>

    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?php

    /**
     * This uses the HTML view helper to include a <title> tag use the app.name directive in your application.ini file.
     */
    echo $this->html->title($this->application->config->app['name']);

    /**
     * This import() method is very important.  It is used to generate any <script> or <link> tags that are required by
     * any views and view helpers that you are using.  Without this, you may find some feature of HazaarMVC view helper
     * ecosystem will not work
     */
    echo $this->import();

    /**
     * You can also import a stylesheet directly using the style() method of the HTML view helper.
     */
    echo $this->html->link('main.css');
    ?>

</head>
<body class="<?=$this->application->config->app['theme']['name']; ?>">

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><?=$this->application->config->app['name']; ?></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><?=$this->html->a($this->application->url(), 'Home'); ?></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Documentation</li>
                        <li><?=$this->html->a('http://hazaar.io', 'Hazaar MVC Website'); ?></li>
                        <li><?=$this->html->a('https://scroly.io/hazaarmvc', 'Online Documentation'); ?></li>
                        <li><?=$this->html->a('https://scroly.io/hazaarmvc/page/api', 'API Reference'); ?></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Support</li>
                        <li><?=$this->html->a('http://git.funkynerd.com/hazaar/hazaar-mvc/issues', 'Support Issues'); ?></li>
                        <li><?=$this->html->a('http://git.funkynerd.com/hazaar/hazaar-mvc/issues/new', 'Create Issue'); ?></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!--/.navbar-collapse -->
    </div>
</div>

<div class="container">

    <?=$this->layout(); ?>

    <hr/>

    <footer>
        <p>&copy; Jamie Carl - 2015</p>

        <p class="text-center"><?=$this->html->poweredby(); ?></p>
    </footer>

</div>

<?=$this->post(); ?>

</body>
</html>
    
