<div class="jumbotron">
    <?=$this->html->block('h1', $this->getWelcomeString()); ?>
    <p>Congratulations! You have successfully installed the Hazaar MVC framework example application. You are currently
        running
        Hazaar MVC version <?=$this->application->version(); ?>. This example application is a good starting point
        for building your
        own application with Hazaar MVC.</p>

    <p><?=$this->html->a('http://www.hazaarmvc.com', 'Vist the Website &raquo;', array('class' => 'btn btn-primary btn-large')); ?></p>
</div>

<!-- Example row of columns -->
<div class="row">
    <div class="col-lg-8">
        <h2>Follow Development</h2>

        <p>Hazaar MVC is constantly under development and is growing constantly. To keep up to date on new features feel
            free to checkout
            the roadmap page on the Hazaar MVC development website. You can also view the documentation
            <?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/wiki', 'wiki'); ?>,
            <?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/news', 'dev blog'); ?>,
            <?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/issues', 'issue tracker'); ?>,
            and much, much more. The development website is the main hub and a great resource for everything related to
            the development
            of Hazaar MVC.</p>

        <p><?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/roadmap', 'View the Roadmap &raquo;', array('class' => 'btn')); ?></p>
    </div>
    <div class="col-lg-4">
        <h2>Help & Support</h2>

        <p>If you need any help or support developing with Hazaar MVC then feel free to drop by the
            <?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/boards', 'support forums'); ?> and ask your
            questions. The Hazaar MVC
            support staff or other users will be able to help you out.</p>

        <p><?=$this->html->a('http://dev.funkynerd.com/projects/hazaar/boards', 'Visit the Forums &raquo;', array('class' => 'btn')); ?></p>
    </div>
</div>
