stages:
  - build
  - test

variables:
  APPLICATION_PATH: .
  UNIT_TEST_IMAGE: $CI_REGISTRY_IMAGE/ci_unit_test_image

Build Test Image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - until docker info; do sleep 1; done
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --network host --pull --rm -f "Dockerfile" -t $CI_REGISTRY_IMAGE .
    - docker push --all-tags $CI_REGISTRY_IMAGE

# Coding Standard:
#   stage: test
#   image: composer
#   before_script:
#     - composer install
#   script:
#     - vendor/bin/phpcs src --report-junit=phpcs-test-results.xml
#   artifacts:
#     when: always
#     reports:
#       junit: phpcs-test-results.xml

Code Quality:
  stage: test
  image: overtrue/phplint:latest
  variables:
    INPUT_PATH: "./src"
    INPUT_OPTIONS: "-c .phplint.yml"
  script: /home/appuser/.composer/vendor/bin/phplint -c .phplint.yml
  artifacts:
    when: always
    reports:
      junit: phplint-test-results.xml

Static Analysis:
  stage: test
  image: composer
  before_script:
    - composer install
  script:
    - vendor/bin/phpstan analyse -c phpstan.neon --error-format=junit > phpstan-test-results.xml
  artifacts:
    when: always
    reports:
      junit: phpstan-test-results.xml

Unit Testing:
  stage: test
  image: $UNIT_TEST_IMAGE:latest
  variables:
    APPLICATION_PATH: tests/application
  before_script:
    - composer install
  script:
    - vendor/bin/phpunit
  artifacts:
    when: always
    reports:
      junit: phpunit-test-results.xml

