stages:
  - docker
  - test

variables:
  UNIT_TEST_IMAGE: $CI_REGISTRY_IMAGE

Docker:
  image: docker:20.10.12
  stage: docker
  services:
    - docker:20.10.12-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --network host --pull --rm -f "Dockerfile" -t $UNIT_TEST_IMAGE:latest .
    - docker push --all-tags $UNIT_TEST_IMAGE
  rules:
    - changes:
      - Dockerfile

Test:
  image: $UNIT_TEST_IMAGE:latest
  stage: test
  script:
    - composer install
    - vendor/bin/phplint src
    - vendor/bin/phpunit

Semgrep-SAST:
  image: semgrep/semgrep
  script: semgrep ci
  rules:
  - if: $CI_PIPELINE_SOURCE == "web"  # allow triggering a scan manually from the gitlab UI
  - if: $CI_MERGE_REQUEST_IID  # scan on merge request events
  - if: $CI_COMMIT_BRANCH == "legacy"  # scan on push events to default branch
  variables:
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    # To configure MR comments on gitlab.com, see https://semgrep.dev/docs/semgrep-cloud-platform/gitlab-mr-comments/#steps-to-set-up-mr-comments
    # GITLAB_TOKEN: $PAT
