stages:
  - docker
  - test

Docker:
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  script:
    - docker build --pull --rm -f "Dockerfile" -t hazaar_cicd_image:latest "."
    - docker tag hazaar_cicd_image $DOCKER_USERNAME/hazaar_cicd_image
    - docker push $DOCKER_USERNAME/hazaar_cicd_image:latest
  rules:
    - changes:
      - Dockerfile

Test:
  image: jamiecarl/hazaar_cicd_image
  script:
    - composer install
    - vendor/bin/phplint src
    - vendor/bin/phpunit
