
<h1>Synchronise Data</h1>

<div class="row">
    <div class="col col-md-12">
        <div style="margin-bottom: 15px;">
            <form id="frmSync">
                <button type="submit" class="btn btn-primary">Sync Data</button>
            </form>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Data Sync Log</div>
            <div id="synclog" class="panel-body"></div>
        </div>
    </div>
</div>

