<div id="joblist" class="section">

</div>

<script>
    <?php foreach($this->status['queue'] as $id => $job) {
        $data = array(
            'Status' => strtoupper($job['status_text']),
            'ID' => $job['id'],
            'Start' => $this->datetime($job['start']),
            'Environment' => $job['application']['env'],
            'Retries' => $job['retries']
        );

        echo "displayPanel($('#joblist'), '$id', '$job[tag]', " . json_encode($data) . ");";

    } ?>

</script>

