<div class="section" id="servicelist">

</div>

<script>
    <?php foreach($this->status['services'] as $name => $service) {

        $data = array(
            'Status' => $service['status'],
            'Restarts' => $service['restarts'],
            'Heartbeats'=> $service['heartbeats'],
            'Last Heartbeat'=> $this->datetime($service['last_heartbeat'])
        );

        $state = ($service['enabled'])?'Disable':'Enable';

        echo "var buttons = $('<div class=\"pull-right\">').append([
                $('<button class=\"btnTestService\">').html('Test'),
                $('<button class=\"btnToggleService\">').html('$state')
                ]).attr('data-service', '$name');\n";

        echo "displayPanel($('#servicelist'), '$name', '$name', " . json_encode($data) . ", buttons);";
    } ?>

    $(document).ready(function () {
        var list = $('#servicelist');
        list.find('.btnToggleService').click(function () {
            if ($(this).html() == 'Enable') {
                warlock.enable($(this).parent().attr('data-service'));
                $(this).html('Disable');
            } else {
                warlock.disable($(this).parent().attr('data-service'));
                $(this).html('Enable');
            }
        });
        list.find('.btnTestService').click(function () {
            $(this).html('Testing').attr('disabled', true);
            $.post('<?=$this->url('test');?>', {service: $(this).parent().attr('data-service')}).always(function () {
                list.find('.btnTestService').html('Test').attr('disabled', false);
            }).done(function (data) {
                console.log(data.results);
                if (data.result == 'ok') {
                    var msg = $('<div>');
                    msg.append($('<div>').html('Server reports no errors with the service.').css({'margin-bottom': '15px'}));
                    for (x in data.results) {
                        msg.append($('<div>').html(x + ': ' + data.results[x]));
                    }
                    $('<div>').html(msg).dialog({title: 'Success'});

                } else
                    $('<div>').html(data.reason).dialog({title: 'Error'});
            }).fail(function (xhr, textStatus, errorThrown) {
                var data = JSON.parse(xhr.responseText);
                if (data.error) {
                    $('<div>').html(data.error.str + ' on line #' + data.error.line + ' in ' + data.error.file).dialog({title: 'Error'});
                }
            });
        });
    });
</script>