<?php

declare(strict_types=1);

namespace Hazaar\Controller;

use Hazaar\Application\Route;
use Hazaar\Controller;
use Hazaar\Controller\Response\JSON;
use Hazaar\Controller\Response\Text;
use Hazaar\File;
use Hazaar\View;

/**
 * Class Closure.
 *
 * This class extends the base Controller class and is designed to handle closures.
 * It provides functionality to execute a closure and return a response based on the closure's output.
 */
class Closure extends Controller
{
    protected \Closure $closure;

    public function __construct(\Closure $closure)
    {
        parent::__construct();
        $this->closure = $closure;
    }

    /**
     * Executes the closure associated with this controller and returns a Response.
     *
     * @param null|Route $route optional route parameter
     *
     * @return Response The response generated by the closure. The response can be of different types:
     *                  - If the closure returns an instance of Response, it is returned directly.
     *                  - If the closure returns an instance of File, it is wrapped in a Response\File object.
     *                  - If the closure returns an array or an object, it is wrapped in a JSON response.
     *                  - Otherwise, the response is wrapped in a Text response.
     */
    public function runRoute(?Route $route = null): Response
    {
        $boundClosure = $this->closure->bindTo($this, self::class);
        $response = call_user_func_array($boundClosure, $route->getActionArgs());
        if ($response instanceof Response) {
            return $response;
        }
        if ($response instanceof File) {
            return new Response\File($response);
        }
        if ($response instanceof View) {
            return new Response\View($response);
        }
        if (is_array($response) || is_object($response)) {
            return new JSON($response);
        }

        return new Text($response);
    }
}
