<?php

declare(strict_types=1);

namespace Hazaar\Controller;

use Hazaar\Application\Request;
use Hazaar\Application\Request\HTTP;
use Hazaar\Controller\Response\HTTP\OK;
use Hazaar\Controller\Response\XML;
use Hazaar\File;
use Hazaar\File\Dir;
use Hazaar\File\Manager;
use Hazaar\XML\Element;

abstract class WebDAV extends Basic
{
    /**
     * @var HTTP
     */
    protected Request $request;
    protected Manager $manager;
    private string $__propset = '<http://apache.org/dav/propset/fs/1>';

    /**
     * @var array<int>
     */
    private array $__dav_classes = [1];

    /**
     * @var array<string>
     */
    private array $__allowed_methods = [
        'OPTIONS',
        'GET',
        'HEAD',
        'POST',
        'DELETE',
        'TRACE',
        'PROPFIND',
        'PROPPATCH',
        'COPY',
        'MOVE',
        'LOCK',
    ];

    /**
     * Executes the specified action for the WebDAV controller.
     *
     * @param string       $actionName      the name of the action to execute
     * @param array<mixed> $actionArgs      Optional. The arguments to pass to the action. Default is an empty array.
     * @param bool         $namedActionArgs Optional. Whether the action arguments are named. Default is false.
     *
     * @return Response the response generated by the action
     *
     * @throws \Exception if named action arguments are used, if the media source is unknown, if the method is not supported, or if the response is not an instance of Response
     */
    public function runAction(string $actionName, array $actionArgs = [], bool $namedActionArgs = false): Response
    {
        if (true === $namedActionArgs) {
            throw new \Exception('Named action arguments are not supported for WebDAV actions.');
        }
        if ('index' !== $actionName) {
            if (($this->manager = Manager::select($actionName)) === false) {
                throw new \Exception('Unknown media source!', 404);
            }
        }
        $method = strtolower($this->request->getMethod());
        // If the method is not supported, check for a __default handler to pass it off to, or else 405.
        if (!(in_array(strtoupper($method), $this->__allowed_methods) && method_exists($this, $method))) {
            if (!method_exists($this, '__default')) {
                throw new \Exception('Method not supported', 405);
            }

            return $this->__default($this->name, $actionName);
        }
        $response = call_user_func([$this, $method]);
        if ($this->stream) {
            $response = new Response\Stream($response);
        }
        if (!$response instanceof Response) {
            throw new \Exception('Internal Server Error', 500);
        }

        return $response;
    }

    /**
     * Handles the OPTIONS HTTP method for the WebDAV controller.
     *
     * This method generates a response indicating the allowed HTTP methods
     * and the WebDAV capabilities supported by the server.
     *
     * @return Response the response object containing the allowed methods and WebDAV capabilities
     */
    public function options(): Response
    {
        $response = new OK();
        $response->setContentType('httpd/unix-directory');
        $response->setHeader('DAV', implode(',', $this->__dav_classes));
        $response->setHeader('DAV', $this->__propset, false);
        // Only allow methods that are listed and also have a callable function
        $methods = array_intersect(array_map('strtoupper', get_class_methods($this)), $this->__allowed_methods);
        $response->setHeader('Allow', implode(',', $methods));

        return $response;
    }

    /**
     * Handles the PROPFIND request for WebDAV.
     *
     * This method processes a PROPFIND request, which is used to retrieve properties for a resource identified by the request URI.
     * It supports Depth headers of 0 and 1, but throws an exception for Depth headers of "infinity".
     *
     * @return Response the XML response containing the properties of the requested resource
     *
     * @throws \Exception if the Depth header is "infinity" or if the Depth header is not 0 or 1
     */
    public function propfind(): Response
    {
        $path = '/'.ltrim($this->request->getPath(), '/');
        $depth = $this->request->hasHeader('Depth') ? $this->request->getHeader('Depth') : 'infinity';
        if ('infinity' === strtolower($depth)) {
            throw new \Exception('PROPFIND requests with a Depth of "infinity" are not allowed for '.$path.'.');
        }
        $depth = (int) $depth;
        if (0 !== $depth && 1 !== $depth) {
            throw new \Exception('Bad request', 400);
        }
        date_default_timezone_set('UTC');
        $object = $this->manager->get($path);
        $xml = new Element();
        $xml->addNamespace('D', 'DAV:');
        $ms = $xml->add('D:multistatus');
        $this->writeObjectStatusResponse($object, $ms);
        if (1 === $depth && $object instanceof Dir) {
            while ($child = $object->read()) {
                $this->writeObjectStatusResponse($child, $ms);
            }
        }
        $response = new XML($xml);
        $response->setStatus(207);

        return $response;
    }

    /**
     * Handles the PROPPATCH WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function proppatch(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the LOCK WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function lock(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the POST WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function post(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the COPY WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function copy(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the MOVE WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function move(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the DELETE WebDAV method.
     *
     * @throws \Exception thrown when the method is not implemented
     */
    public function delete(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Handles the TRACE HTTP method.
     *
     * @throws \Exception indicates that the TRACE method is not currently implemented
     */
    public function trace(): Response
    {
        throw new \Exception(__METHOD__.' not currently implemented!', 403);
    }

    /**
     * Generates and writes the XML response for a given Dir or File object.
     *
     * This method constructs an XML response that includes various properties
     * of the provided Dir or File object, such as its full path, creation date,
     * last modified date, content length (for files), and more. The response
     * adheres to the WebDAV protocol.
     *
     * @param Dir|File $object the directory or file object for which the response is generated
     * @param Element  $xml    the XML element to which the response is added
     *
     * @return Element the generated XML response element
     */
    private function writeObjectStatusResponse(Dir|File $object, Element $xml): Element
    {
        $response = $xml->add('D:response');
        $response->addNamespace('lp1', 'DAV:');
        $response->addNamespace('lp2', 'http://apache.org/dav/props/');
        $response->add('D:href', $object->fullpath());
        $propstat = $response->add('D:propstat');
        $prop = $propstat->add('D:prop');
        $type = $prop->add('lp1:resourcetype');
        if ($object instanceof Dir) {
            $type->add('D:collection');
        }
        $prop->add('lp1:creationdate', date('c', $object->ctime()));
        $prop->add('lp1:getlastmodified', date('c', $object->mtime()));
        if ($object instanceof File) {
            $prop->add('lp1:getcontentlength', $object->size());
            $prop->add('lp2:executable', 'F');
        }
        $prop->add('lp1:getetag', '14-5959eb7f60805');
        $prop->add('D:supportedlock');
        $prop->add('D:getcontenttype', $object->mimeContentType());
        $propstat->add('D:status', $object->exists() ? 'HTTP/1.1 200 OK' : 'HTTP/1.1 404 Not Found');

        return $response;
    }
}
