<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Media Browser</title>

    <style>
        body,html { position: absolute; top: 0; right: 0; bottom: 0; left: 0; margin: 0; }
        #mediabrowser { width: 100%; }
    </style>

    <?=$this->import();?>

</head>
<body>

    <?php
    
        $fb = $this->filebrowser->get('mediabrowser')
            ->width('100%')->height('100%')
            ->showinfo(true)
            ->useMeta(true);
    
        if($this->application->request->has('root')){

            list($source, $path) = explode(':', $this->application->request->root, 2);

            $fb->root($source, $path);

        }

        echo $fb;
    ?>

    <?=$this->post();?>

    <script>
    $(document).ready(function(){
        $('#mediabrowser').on('select', function(e, item){
            window.open(item[0].link, '_blank');
        });
    });
    </script>

</body>
</html>
