
<div class="row">
    <div class="col col-12">
        <div class="panel primary">
            <div data-bind="row[0].name">Waiting</div>
        </div>
        <div class="panel">
            <div class="panel-header">Configuration Files</div>
            <div class="panel-content">
                <table class="table" id="configFiles">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Size</th>
                            <th>Encrypted</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

            </div>
        </div>
    </div>
</div>
