
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Signin Template for Bootstrap</title>

    <?=$this->import();?>
</head>

<body>

    <div class="container">

        <form class="form-signin" action="<?=$this->url('login');?>" method="POST">
            <?php if($this->msg) echo $this->html->div($this->msg)->class('alert alert-danger');?>
            <h2 class="form-signin-heading">Please sign in</h2>
            <label for="inputUser" class="sr-only">User name</label>
            <input type="text" id="inputUser" name="username" class="form-control" placeholder="User name" required autofocus />
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required />
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>

    </div>

</body>
</html>
