
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Signin Template for Bootstrap</title>

    <?=$this->import();?>

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" />

</head>

<body>

    <div class="login-bg">
        <div class="overlay"></div>
    </div>

    <div class="container">

        <form class="form-signin" action="<?=$this->url('login');?>" method="POST">

            <div class="login-heading">
                <h1>Hazaar MVC</h1>
                <h4>Application Console</h4>
            </div>

            <?php if($this->msg) echo $this->html->div($this->msg)->class('alert');?>

            <div class="login-icon"></div>

            <h3 class="form-signin-heading">Please sign in</h3>

            <p class="login-text">Unauthorised access is prohibited.</p>

            <div class="form-group">
                <input type="text" id="inputUser" name="username" placeholder="&#61447; user name" required autofocus />
            </div>

            <div class="form-group">
                <input type="password" id="inputPassword" name="password" placeholder="&#61572; Password" required />
            </div>

            <button class="btn btn-lg btn-hazaar btn-block" type="submit">Sign in</button>
        </form>

    </div>

</body>
</html>
