
<ul class="sidebar-nav-module">
    <?php
    foreach($this->items as $item){

        if($active = $this->active($item->target))
            $this->setActiveMenu($item);

        $a = $this->html->a($this->url($item->target), array(
            $item->icon ? $this->fontawesome->icon($item->icon) : null,
            $item->label
        ));

        if($item->suffix)
            $a->add($this->html->span(ake($item->suffix, 0))->class('suffix ' . ake($item->suffix, 1, 'default')));

        $li = $this->html->li($a)->class('sidebar-nav-item')->toggleClass('selected', $active);

        if($active && $item->items)
            $li->add($this->partial('menu', array('items' => $item->items)));

        echo $li;

    }
    ?>
</ul>
<?php

