
<form style="height: 100%;" method="post">
    <div class="row row-full">
        <div class="col col-12">
            <div class="panel panel-full">
                <div class="panel-header">Application Configuration</div>
                <div class="panel-content">
                    <textarea name="config" style="width: 100%; height: 100%;"><?=$this->config;?></textarea>
                </div>
                <div class="panel-footer">
                    <button class="primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>