
<div class="row">
    <div class="col col-12">
        <div class="panel">
            <div class="panel-header">Configuration Files</div>
            <div class="panel-content">
                <table class="table" id="encryptFiles">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Size</th>
                            <th>Writable</th>
                            <th>Encryption</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
