


<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>File</th>
            <th>Size</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->items as $item): ?>
        <tr>
            <td>
                <?=$item->name();?>
            </td>
            <td>
                <?=$item->relativepath();?>
            </td>
            <td>
                <?=str_bytes($item->size());?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>